In [2]:
import gffpandas.gffpandas as gffpd

import pandas as pd
from pandas.core.common import SettingWithCopyWarning
import gseapy as gp
import warnings

import numpy as np
from gseapy.plot import barplot, dotplot
from matplotlib import pyplot as plt 


warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

path_to_data='/Users/aleksandradenisova/Desktop/coursework/data/stage2'

In [4]:
annotation = gffpd.read_gff3('{}/{}'.format(path_to_data, 'GCF_003957565.2_bTaeGut1.4.pri_genomic.gff'))

In [37]:
df_ori = annotation.df
df = df_ori[df_ori['type'].isin(['gene', 'lnc_RNA', 'exon', 'mRNA', 'CDS', 'tRNA',
       'transcript', 'primary_transcript', 'miRNA', 'pseudogene',
       'snoRNA', 'guide_RNA', 'snRNA', 'C_gene_segment', 'V_gene_segment', 'rRNA', 'sequence_feature'])]

df['GeneId'] = df['attributes'].apply(lambda x: x.split(';')[0].split('=')[1].split('-')[1])
df.head()

,seq_id,source,type,start,end,score,strand,phase,attributes,chrom,GeneId
1,NC_044211.2,Gnomon,gene,6695,12279,.,+,.,ID=gene-LOC121470777;Dbxref=GeneID:121470777;N...,NC_044211.2,LOC121470777
2,NC_044211.2,Gnomon,lnc_RNA,6695,12279,.,+,.,ID=rna-XR_005981978.1;Parent=gene-LOC121470777...,NC_044211.2,XR_005981978.1
3,NC_044211.2,Gnomon,exon,6695,6759,.,+,.,ID=exon-XR_005981978.1-1;Parent=rna-XR_0059819...,NC_044211.2,XR_005981978.1
4,NC_044211.2,Gnomon,exon,7790,7996,.,+,.,ID=exon-XR_005981978.1-2;Parent=rna-XR_0059819...,NC_044211.2,XR_005981978.1
5,NC_044211.2,Gnomon,exon,8177,12279,.,+,.,ID=exon-XR_005981978.1-3;Parent=rna-XR_0059819...,NC_044211.2,XR_005981978.1

In [45]:
df_genes = pd.read_csv('~/Desktop/coursework/data/final_data/positions_0.05_ANOVA_inno_zibra.vcf.txt',
            sep='\t',
            skiprows=1)
df_genes.head()

,#GeneName,GeneId,TranscriptId,BioType,variants_impact_LOW,variants_impact_MODERATE,variants_impact_MODIFIER,variants_effect_3_prime_UTR_variant,variants_effect_5_prime_UTR_premature_start_codon_gain_variant,variants_effect_5_prime_UTR_variant,variants_effect_downstream_gene_variant,variants_effect_intron_variant,variants_effect_missense_variant,variants_effect_non_coding_transcript_exon_variant,variants_effect_splice_region_variant,variants_effect_synonymous_variant,variants_effect_upstream_gene_variant
0,ADAMTS2,ADAMTS2,XM_030283925.3,protein_coding,0,0,2,0,0,0,0,2,0,0,0,0,0
1,ADSS2,ADSS2,XM_012572420.4,protein_coding,0,0,3,0,0,0,0,3,0,0,0,0,0
2,ADSS2,ADSS2,XM_041715289.1,protein_coding,0,0,3,0,0,0,0,3,0,0,0,0,0
3,AFAP1L2,AFAP1L2,XM_030276462.3,protein_coding,0,0,2,0,0,0,0,2,0,0,0,0,0
4,AFAP1L2,AFAP1L2,XM_030276463.3,protein_coding,0,0,2,0,0,0,0,2,0,0,0,0,0

In [42]:
df_mereged = df_genes.merge(df[['GeneId','type']], on = 'GeneId', how='left')
df_mereged['type'].unique()

array(['gene', nan], dtype=object)

In [44]:
df_mereged[df_mereged['type'].isna()]

,#GeneName,GeneId,TranscriptId,BioType,variants_impact_LOW,variants_impact_MODERATE,variants_impact_MODIFIER,variants_effect_3_prime_UTR_variant,variants_effect_5_prime_UTR_premature_start_codon_gain_variant,variants_effect_5_prime_UTR_variant,variants_effect_downstream_gene_variant,variants_effect_intron_variant,variants_effect_missense_variant,variants_effect_non_coding_transcript_exon_variant,variants_effect_splice_region_variant,variants_effect_synonymous_variant,variants_effect_upstream_gene_variant,type
1884,TRNAP-AGG_1,TRNAP-AGG_1,unassigned_transcript_15,protein_coding,0,0,1,0,0,0,1,0,0,0,0,0,0,NaN
1885,TRNAP-CGG,TRNAP-CGG,unassigned_transcript_14,protein_coding,0,0,1,0,0,0,0,0,0,0,0,0,1,NaN

In [49]:
df_ann = pd.read_csv('/Users/aleksandradenisova/programs/snpEff/positions_0.05_ANOVA_inno_zibra.vcf.ann', 
                     skiprows=6,
                     sep = '\t', 
                     names = ['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'FILTER', 'smth','INFO'])

df_ann['type'] = df_ann['INFO'].apply(lambda x: x.split('|')[1])
df_ann['gene_name'] = df_ann['INFO'].apply(lambda x: x.split('|')[3])
df_ann['effect'] = df_ann['INFO'].apply(lambda x: x.split('|')[2])
df_ann.head()

,#CHROM,POS,ID,REF,ALT,FILTER,smth,INFO,type,gene_name,effect
0,NC_044211.2,123676,.,T,"T,C,A",.,.,ANN=A|intron_variant|MODIFIER|CMSS1|CMSS1|tran...,intron_variant,CMSS1,MODIFIER
1,NC_044211.2,544931,.,T,"T,C,A",.,.,ANN=A|intron_variant|MODIFIER|LOC100222962|LOC...,intron_variant,LOC100222962,MODIFIER
2,NC_044211.2,2727694,.,A,"G,C",.,.,ANN=C|intron_variant|MODIFIER|MYH15|MYH15|tran...,intron_variant,MYH15,MODIFIER
3,NC_044211.2,2760307,.,T,"T,G,C,A",.,.,ANN=A|intron_variant|MODIFIER|CIP2A|CIP2A|tran...,intron_variant,CIP2A,MODIFIER
4,NC_044211.2,5048551,.,G,A,.,.,ANN=A|intron_variant|MODIFIER|LOC100220100|LOC...,intron_variant,LOC100220100,MODIFIER

In [57]:
df_ann[df_ann['gene_name']=='TRNAP-CGG']

,#CHROM,POS,ID,REF,ALT,FILTER,smth,INFO,type,gene_name,effect
7,NC_044211.2,14926206,.,T,C,.,.,ANN=C|upstream_gene_variant|MODIFIER|TRNAP-CGG...,upstream_gene_variant,TRNAP-CGG,MODIFIER

WARNING_TRANSCRIPT_NO_START_CODON: игнорируем, нашей тРНК старт-кодон и не нужен

In [55]:
df_ann[df_ann['gene_name']=='TRNAP-CGG']['INFO'].loc[7].split(',')

['ANN=C|upstream_gene_variant|MODIFIER|TRNAP-CGG|TRNAP-CGG|transcript|unassigned_transcript_14|protein_coding||c.-3282T>C|||||3282|WARNING_TRANSCRIPT_NO_START_CODON',
 'C|downstream_gene_variant|MODIFIER|TRNAP-AGG_1|TRNAP-AGG_1|transcript|unassigned_transcript_15|protein_coding||c.*3748A>G|||||3748|WARNING_TRANSCRIPT_NO_START_CODON',
 'C|intron_variant|MODIFIER|RCSD1|RCSD1|transcript|XM_030263664.3|protein_coding|6/6|c.*13+386T>C||||||',
 'C|intron_variant|MODIFIER|RCSD1|RCSD1|transcript|XM_030263670.3|protein_coding|5/5|c.*13+386T>C||||||']

#### Вывод: 

есть предположение, что эта мутация находится на участке между пролиновыми тРНК: после последовательности, которая кодирует тРНК с антикодоном AGG, но перед последовательностью, кодирующей тРНК с антикодоном CGG